core/urls.py
from django.urls import path

from core.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    mark_is_complete,
    mark_not_complete,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path("tasks/done/<int:pk>/", mark_is_complete, name="done"),
    path("tasks/undone/<int:pk>/", mark_not_complete, name="undone"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),

]

app_name = "core"

to_do/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls", "core")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(
        max_length=255,
        unique=True,
        blank=False,
        null=False
    )

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField(blank=False, null=False)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(
        Tag,
        blank=False,
        null=False,
        related_name='tasks',
    )

    @property
    def is_finished(self):
        return "Done" if self.is_done else "Not Done"

    def __str__(self):
        return f"{self.content} ({self.is_finished})"

core/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from core.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 5
    ordering = ['is_done', '-datetime']


class TaskCreateView(generic.CreateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('core:task-list')


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = '__all__'
    success_url = reverse_lazy('core:task-list')


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy('core:task-list')


class TagListView(generic.ListView):
    model = Tag
    context_object_name = 'tag_list'
    template_name = 'core/tag_list.html'
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = '__all__'
    success_url = reverse_lazy("core:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = '__all__'
    success_url = reverse_lazy("core:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("core:tag-list")


def mark_is_complete(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, pk=pk)
    task.is_done = True
    task.save()
    return HttpResponseRedirect(
        request.META.get("HTTP_REFERER",
                         reverse_lazy(viewname="core:index"))
    )


def mark_not_complete(request: HttpRequest, pk: int) -> HttpResponse:
    task = get_object_or_404(Task, pk=pk)
    task.is_done = False
    task.save()
    return HttpResponseRedirect(
        request.META.get("HTTP_REFERER",
                         reverse_lazy(viewname="core:index"))
    )

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/core/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'core:tag-list' %}" class="btn btn-success link-to-page">No, get back</a>
  </form>
{% endblock %}

templates/core/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/core/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tag List
    <a href="{% url 'core:tag-create' %}" class="btn btn-success link-to-page">
      Add a new tag
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>

          <td>
              <a href="{% url 'core:tag-update' pk=tag.id %}" class="btn btn-secondary">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'core:tag-delete' pk=tag.id %}" class="btn btn-danger">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/core/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'core:task-list' %}" class="btn btn-success link-to-page">No, get back</a>
  </form>
{% endblock %}

templates/core/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/core/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Task list
    <a href="{% url 'core:task-create' %}" class="btn btn-primary link-to-page">
      Create new task
    </a>
  </h1>
  {% if task_list %}
    {% for task in task_list %}

        <h4><p>{{ task.content }}
          {% if task.is_done %}
          <span style="color:limegreen">{{ task.is_finished }}</span>
          {% else %}
          <span style="color:red">{{ task.is_finished }}</span>
          {% endif %}
        </p></h4>
        {% if task.is_done %}
          <a href="{% url 'core:undone' pk=task.id %}" class="btn btn-outline-secondary">Undo</a>
        {% else %}
          <a href="{% url 'core:done' pk=task.id %}" class="btn btn-outline-success">Complete</a>
        {% endif %}
        <br>
        Created: {{ task.datetime }} {% if task.deadline %}<p style="color:darkred"> Deadline: {{ task.deadline }} </p>{% endif %}<br>
        Tags: {% for tag in task.tags.all %}
        {{ tag }},
        {% endfor %}
      <br>
      <a href="{% url 'core:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
        Delete
      </a>

      <a href="{% url 'core:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">
        Update
      </a>
      <hr>
    {% endfor %}

  {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'core:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'core:tag-list' %}">All tags</a></li>
</ul>